In [46]:
import numpy as np
import matplotlib.pyplot as pd

x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


ARRAY

In [45]:
x = [1,2,3,5]
y = np.array([1,2,3])
print(y)
print(type(y)) ## For array type
print(y.ndim) ## For dimension type

[1 2 3]
<class 'numpy.ndarray'>
1


In [47]:
x = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(x)
print(x.ndim)  ##for dimension of array


[[0 0 0]
 [0 0 0]
 [0 0 0]]
2


Arthmetic Operatons  "ADDITION"

In [55]:
x = np.array([[1,2],[2,0]])
y = np.array([[11,21],[12,23]])
z = x @ y
print(z)

[[35 67]
 [22 42]]


SUBTRATION

In [51]:
x = np.array([[1,4,3],[2,3,1]])
y = np.array([[1,2,2],[1,3,2]])
z = x-y
print(z)

[[ 0  2  1]
 [ 1  0 -1]]
